### ISSUE TITLE
having some trouble importing shapes into notebook.

### ISSUE THREAD

**Issue by Mikejmnez** [sciserver/poseidon-viewer#4]
II tried to export a shape polygon into a jupyter notebook, and get the following `MaxTryError` and `SSLError`

<img width="856" alt="Screen Shot 2022-09-04 at 4 21 12 PM" src="https://user-images.githubusercontent.com/8241481/188332036-17789825-2115-4498-919d-8d021651ba9b.png">

<img width="1263" alt="Screen Shot 2022-09-04 at 4 21 23 PM" src="https://user-images.githubusercontent.com/8241481/188332041-d261ba86-bbd7-4dae-8179-44eff0660789.png">

I get the errors after after executing the following lines on a Notebook using the Oceanography Kernel:

```python
from poseidon_viewer import get_shapes
p = get_shapes()
```

Steps that I follow to reproduce the error:
1. I am working remotely (this may or may be an issue).
2. I am using a newly created container using the Oceanography (Integrated Viewer) image.
3. The `poseidon-viewer app` is opened from the base path (is this still the way it has to be, or can we open the viewer from any other directory?)
4. Select the following a closed polygon defined by the following coordinates NW=(72, -70), SW = (11, -70), SE = (11, 24), NE=(72, 24).
5. Select Save and Export tool bottoms (I do see the message `exported to clipboard`.
6. Run the lines above.

**Comment by Mikejmnez** [comment]
@dmedv Hi Mitya, I am still having some issues trying to play with this. Have you had a chance to look into this issue?

**Comment by dmedv** [comment]
@Mikejmnez Actually, this particular error seems to be an SSL related problem on the web proxy end, not a bug in the code. Our sysadmins are looking into it.

**Comment by Mikejmnez** [comment]
Thanks @dmedv . This week I have been playing with the `poseidon viewer` and it works well! I will be closing this issue, since the error above is no longer reproduced
