### ISSUE TITLE
Edit points in data selection tool

### ISSUE THREAD

**Issue by ThomasHaine** [sciserver/poseidon-viewer#7]
@dmedv Can you add functionality to edit the way-points defined in the point, line segment, and polygon cutout selection tool?  E.g., I make a sequence of points to define a line segment and copy the `JSON` object. But then I need to adjust the position of the points. Currently, I have to delete the line segment and start over. Can I drag and drop the existing points instead?

**Comment by dmedv** [comment]
It is already possible to adjust the points in a line segment by dragging them. You need to select the line segment tool and move the cursor over the old line. You can also add new points by dragging the middle of a straight segment, or remove points by clicking them while holding the <Alt> key. I will describe it properly in the documentation, also it might be worth recording a video in this case.

**Comment by ThomasHaine** [comment]
Great!
